config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  # get 'users/my_portfolio'
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true
  
  

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key] ,
      secret_token: Rails.application.credentials.iex_client[:secret_access_key] ,
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    # client.price(ticker_symbol)
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.revisar_db(ticker_symbol)
    # Stock.where(ticker:'GOOG')  ya no lleva el Stock porque ya estamos en el Stock model, esta implicito
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def accion_ya_rastreada?(ticker_symbol)
    # esto verifica si la stock existe, no necesariamente si el usuario la tiene, solo checa que exista en la Stock table 
    stock = Stock.revisar_db(ticker_symbol)
    return false unless stock
    # user.stocks.where(id:5) asi lo pongo en consola, pero el user va implicito
    stocks.where(id: stock.id).exists?

  end
  
  def debajo_limite_acciones?
    # user.stocks.count < 10 el user va implicito pq estamos en el modelo user
    stocks.count < 10
  end

  def puede_rastrear_acciones?(ticker_symbol)
    debajo_limite_acciones? && !accion_ya_rastreada?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    'Anonimo'
  end

  def self.search(param)
    # el strip corta los espacios en blanco es como un trim en js
    param.strip!
    reciba_algo = (first_name_coincide(param) + last_name_coincide(param) + email_coincide(param)).uniq
    return nil unless reciba_algo
    reciba_algo
  end

  def self.first_name_coincide(param)
    coincide('first_name', param)
  end

  def self.last_name_coincide(param)
    coincide('last_name', param)
  end
  
  def self.email_coincide(param)
    coincide('email', param)
  end
  

  def self.coincide(tipo_campo, param) 
    # User.where("email like?",  "%example%")
    where("#{tipo_campo} like?",  "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }  
  end
  
  def no_es_amigo_de?(friend_id)
    !friends.where(id: friend_id).exists?
  end
  
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    friendship = Friendship.create(user_id: current_user.id , friend_id: friend.id)

    if friendship.save
      flash[:notice] = "Ahora tu y #{friend.full_name} son amigos"
    else
      flash[:notice] = "Hubo un error con tu solicitud"
    end
    redirect_to my_friends_path
  end

  def destroy
    friend = User.find(params[:id])
    friendship = Friendship.where(user_id: current_user.id , friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Dejaste de seguir a #{friend.full_name} "
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
        # render 'users/my_portfolio'
      else
        respond_to do |format|
          flash.now[:alert] = 'Por favor ingresa un simbolo valido'
          format.js { render partial: 'users/result' }
        end
        # redirect_to my_portfolio_path
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Por favor ingresa un simbolo para buscar'
        format.js { render partial: 'users/result' }
      end
      # redirect_to my_portfolio_path
    end
  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    # si doy click en agregar a mi portafolio, primero revisa si ya se encuentra en la db
    stock = Stock.revisar_db(params[:ticker])

    # Si no esta procede a crear esa stock y le daremos save para que haga hit a la db y tenga id
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end

    # de forma implicita obtiene el id del user y del stock
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "La accion #{stock.name} se agrego con exito a tu portafolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} se elimino con exito del portafolio"
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @acciones_rastreadas = current_user.stocks
  end
  
  def my_friends
    @mis_amigos = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @acciones_rastreadas = @user.stocks
  end
  
  # def search
  #   friend = params[:friend]  estos son los parametros que recibimos de la url
  #   render json: friend
  # end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends.count < 1
        respond_to do |format|
          flash.now[:alert] = 'No se pudo encontrar el usuario'
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Por favor ingresa el nombre del amigo o el correo'
        format.js { render partial: 'users/friend_result' }
      end
    end
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<div class="row row justify-content-md-center">
    <div class="col-md-10 table-responsive">
        <table class="table table-dark table-striped shadow">
            <thead>
                <tr>
                    <th scope="col">Correo</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                <% @mis_amigos.each do |amigo| %>
                <tr>
                    <td> <%= amigo.email %> </td>
                    <td> <%= amigo.full_name %> </td>
                    <td> 
                        <%= link_to "Ver perfil", user_path(amigo), class:'btn btn-primary mb-2'%> 
                        <%= link_to "Dejar de seguir", friendship_path(amigo), method: :delete, data: { confirm: 'Estas seguro?' } , class:'btn btn-warning mb-2'%> 
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="pt-3 mt-1 mb-3 text-muted border-top">
    Ivan Vasquez &copy; 2022 
</footer>

app/views/layouts/_messages.html.erb
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark" style="background-color: #000000;">
    <div class="container">
        <%# <a class="navbar-brand" href="#">Navbar</a> %>
        <%= link_to 'FinanceTracker', root_path, class:'navbar-brand' %>
        <% if current_user %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <% if request.path == my_portfolio_path %>
                            <%= link_to 'Mi portafolio', my_portfolio_path, class:'nav-link active' %>
                        <% else %>
                            <%= link_to 'Mi portafolio', my_portfolio_path, class:'nav-link' %>
                        <% end %>   
                    </li>
                    <li class="nav-item">
                        <% if request.path == my_friends_path %>
                            <%= link_to 'Amigos', my_friends_path, class:'nav-link active' %>
                        <% else %>
                            <%= link_to 'Amigos', my_friends_path, class:'nav-link' %>
                        <% end %>  
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Perfil
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <%= link_to edit_user_registration_path, class:'dropdown-item' do%>
                                <i class="bi bi-pencil-square"></i>
                                Editar perfil
                            <% end %>   
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                </ul>

                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class='nav-item nombre-usuario'>
                        <i class="bi bi-person-circle"></i>
                        <%= current_user.full_name%>
                    </li>
                    <li class='nav-item'>
                        <%= link_to 'Cerrar Sesion', destroy_user_session_path, class:'btn btn-danger logout', method: :delete %>
                    </li>
                </ul>
                <%# <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
                </form> %>
            </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finace Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row row justify-content-md-center">
    <div class="col-md-10 table-responsive">
        <table class="table table-dark table-striped shadow">
            <thead>
                <tr>
                    <th scope="col">Ticker</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Precio</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                <% @acciones_rastreadas.each do |stock| %>
                <tr>
                    <th scope="row"> <%= stock.ticker %> </th>
                    <td> <%= stock.name %> </td>
                    <td> <%= stock.last_price %> </td>
                    <td> 
                        <% if current_user.puede_rastrear_acciones?(stock.ticker) %>
                            <%= link_to "Agregar al portafolio", user_stocks_path(user:current_user, ticker: stock.ticker), class:'btn btn-success', method: :post %>  
                        <% elsif current_user.id != @user.id  %>
                            <span class="badge bg-secondary">
                                Ya estas rastreando
                                <% if !current_user.debajo_limite_acciones? && current_user.accion_ya_rastreada?(stock.ticker) %>
                                    10 acciones y esta accion
                                <% elsif current_user.debajo_limite_acciones? && current_user.accion_ya_rastreada?(stock.ticker) %>
                                    esta accion
                                <% elsif !current_user.debajo_limite_acciones? %>
                                    10 acciones
                                <% end %>
                            </span>
                        <% end %>

                        <% if current_user.id == @user.id %>
                            <%= link_to "Eliminar", user_stock_path(stock), method: :delete, data: { confirm: 'Estas seguro?' } , class:'btn btn-warning'%> 
                        <% end %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/users/_friend_result.html.erb
<div class="row justify-content-md-center">
  <div class="col-md-10">
    <div class='d-inline-block'>
      <%= render 'layouts/messages' %>  
    </div>
  </div>
</div>


<div class="container">
  <% if @friends %>
  <div class="row justify-content-center mb-2 ">
    <% @friends.each do |friend| %>
      <div class="col-12 col-sm-6 col-md-4 bg-white rounded shadow profile mx-2 mb-3">
        <div class="card-body text-center">
          <%# <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp" alt="avatar"
            class="rounded-circle img-fluid" style="width: 150px;"> %>
          <%= image_tag 'user.png', alt: 'icon' %>
          <h5 class="my-3"> <%= friend.full_name %> </h5>
          <p class="text-muted mb-1">Full Stack Developer</p>
          <p class="text-muted mb-4"> <%= friend.email %> </p>
          <div class="d-flex justify-content-center mb-2">
            
            <% if current_user.no_es_amigo_de?(friend.id) %>
              <%= link_to "Seguir", friendships_path(friend: friend),  class:'btn btn-primary' , method: :post%>
            <% else %>
              <span class="badge bg-secondary text-wrap fs-6 py-2">Son amigos</span>
            <% end %>
            
            <%= link_to "Ver perfil", user_path(friend), class:'btn btn-outline-primary ms-1' %> 
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/users/_friend_result.js.erb
<%# alert('Hola mundo') %>
document.querySelector('#amigo-resultado').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/_result.html.erb
<div class="row justify-content-md-center">
  <div class="col-md-10">
    <div class='d-inline-block'>
      <%= render 'layouts/messages' %>  
    </div>
  </div>
</div>

<% if @stock %>
  <div class="row justify-content-md-center amarillo">
    <div class="col-md-10">
      <div class="card card-header d-inline-block" style="background-color: #FFBC42;">
        <strong>Simbolo:</strong> <%= @stock.ticker %>
        <strong>Nombre:</strong> <%= @stock.name %>
        <strong>Precio:</strong> <%= @stock.last_price %> USD
        <% if current_user.puede_rastrear_acciones?(@stock.ticker) %>
          <%= link_to "Agregar al portafolio", user_stocks_path(user:current_user, ticker: @stock.ticker), class:'btn btn-success', method: :post %>  
        <% else %>
          
          <span class="badge bg-secondary">
            Ya estas rastreando
            <% if !current_user.debajo_limite_acciones? && current_user.accion_ya_rastreada?(@stock.ticker) %>
              10 acciones y esta accion
            <% elsif current_user.debajo_limite_acciones? && current_user.accion_ya_rastreada?(@stock.ticker) %>
              esta accion
            <% elsif !current_user.debajo_limite_acciones? %>
              10 acciones
            <% end %>
          </span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_result.js.erb
<%# alert('Hola mundo') %>
document.querySelector('#resultado').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/my_friends.html.erb
<h1 class='mb-5 text-center mt-3 display-4 fw-bold'>Amigos</h1>

<div class="mt-5 row justify-content-md-center buscador">
  <div class="col-md-10">
    <h3>Buscar amigos</h3>  
    <%= form_tag search_friend_path,remote: true, method: :get do%>
      <div class="input-group shadow">
          <%# <input type="text" class="form-control form-control-lg" placeholder="Search Here"> %>
          <%= text_field_tag :friend, params[:friend], placeholder:'Nombre o correo; prueba escribiendo @', autofocus:true, class:'form-control form-control-lg' %>
          <button type="submit" class="input-group-text btn text-white" style="background-color: #5465FF;"><i class="bi bi-search me-2"></i>Buscar</button>
        
      </div>
    <% end %>
  </div>
</div>

<div id="amigo-resultado">

</div>

<% if !@mis_amigos.empty? %>
  <%= render 'friends/list' %>
<% else %>
  <div class="p-5 mb-4 mt-4 rounded-3 shadow text-white" style="background-color: #5465FF;">
    <div class="container-fluid py-5">
      <p class="display-5 fw-bold h1">
        ¿No tienes amigos?
        <svg xmlns="http://www.w3.org/2000/svg" width="46" height="46" fill="currentColor" class="bi bi-emoji-frown-fill" viewBox="0 0 16 16">
          <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm-2.715 5.933a.5.5 0 0 1-.183-.683A4.498 4.498 0 0 1 8 9.5a4.5 4.5 0 0 1 3.898 2.25.5.5 0 0 1-.866.5A3.498 3.498 0 0 0 8 10.5a3.498 3.498 0 0 0-3.032 1.75.5.5 0 0 1-.683.183zM10 8c-.552 0-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5S10.552 8 10 8z"/>
        </svg>
      </p>
      
      <p class="col-md-8 fs-3">Eso no es problema!</p>
      <p class='fs-4'>Si no sabes el correo o el nombre de usuario de tu amigo escribe '@' en el buscador y te apareceran todos los usuarios </p>
    </div>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1 class='text-center mt-3 display-4 fw-bold'>Mi portafolio</h1>

<div class="mt-5 row justify-content-md-center buscador">
  <div class="col-md-10">
    <h3>Buscar Stocks</h3>  
    <%= form_tag search_stock_path, remote: true, method: :get do%>
      <div class="input-group shadow">
          <%# <input type="text" class="form-control form-control-lg" placeholder="Search Here"> %>
          <%= text_field_tag :stock, params[:stock], placeholder:'Example: AAPL', autofocus:true, class:'form-control form-control-lg' %>
          <button type="submit" class="input-group-text btn text-white" style="background-color: #5465FF;"><i class="bi bi-search me-2"></i>Buscar</button>
        
      </div>
    <% end %>
  </div>
</div>

<div id="resultado">
</div>


<% if !@acciones_rastreadas.empty? %>
  <%= render 'stocks/list' %>
<% else %>
  <div class="p-5 mb-4 mt-4 rounded-3 shadow text-white" style="background-color: #5465FF;">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">¿No tienes acciones en tu portafolio?</h1>
      <p class="col-md-8 fs-4">Prueba agregando acciones de las empresas que quieras en el buscador.</p>
      <p>Por ejemplo: AAPL, AMZN, MSFT, NFLX, UBER</p>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<h2 class='mb-5 text-center mt-3 display-4 fw-bold'>Detalles del usuario</h2>

<div class="container">
  <div class="row justify-content-center mb-2 ">
    <div class="col-12 col-sm-6 col-md-4 bg-white rounded shadow profile mx-2 mb-3">
      <div class="card-body text-center">
        <%= image_tag 'user.png', alt: 'icon' %>
        <h5 class="my-3"> <%= @user.full_name %> </h5>
        <p class="text-muted mb-1">Full Stack Developer</p>
        <p class="text-muted mb-4"> <%= @user.email %> </p>
        <div class="d-flex justify-content-center mb-2">
          <% if current_user.no_es_amigo_de?(@user.id) %>
          <%= link_to "Seguir", friendships_path(friend: @user),  class:'btn btn-primary' , method: :post%>
          <% else %>
          <span class="badge bg-secondary text-wrap fs-6 py-2">Son amigos</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if !@acciones_rastreadas.empty? %>
  <%= render 'stocks/list' %>
<% else %>
    <p class='lead text-center'>
        Este usuario no esta siguiendo ninguna accion
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-info-circle-fill" viewBox="0 0 16 16">
            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </svg>
    </p>
<% end %>

app/views/welcome/index.html.erb
<h1 class='mb-4 text-center mt-3 display-2 fw-bold'>Bienvenido a  <em style="color: #5465FF;"> FinanceTracker App</em> </h1>

<div id="carouselExampleIndicators" class="carousel slide mb-3" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag 'stock2.jpg', alt: 'icon', class:'d-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'stock3.jpg', alt: 'icon', class:'d-block w-100' %>
    </div>
    <div class="carousel-item">
      <%= image_tag 'stock6.png', alt: 'icon', class:'d-block w-100' %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<main>
  <div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-bookmarks-fill" viewBox="0 0 16 16">
            <path d="M2 4a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v11.5a.5.5 0 0 1-.777.416L7 13.101l-4.223 2.815A.5.5 0 0 1 2 15.5V4z"/>
            <path d="M4.268 1A2 2 0 0 1 6 0h6a2 2 0 0 1 2 2v11.5a.5.5 0 0 1-.777.416L13 13.768V2a1 1 0 0 0-1-1H4.268z"/>
        </svg>
        <span class="fs-4">Sobre la App</span>
      </a>
    </header>

    <div class="p-5 mb-4 rounded-3 shadow text-white" style="background-color: #212529;">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">¿Como funciona?</h1>
        <p class="col-md-8 fs-4">Explora las funcionalidades para checar los precios de las acciones de las empresas que mas te gusten y agregalas a tu portafolio para darle un mejor seguimiento</p>
        <%= link_to 'Mi portafolio', my_portfolio_path, class:'btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold' %>
      </div>
    </div>

  </div>
</main>